/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerInfoForm.java
 *
 * Created on 2011年3月21日, 下午08:53:39
 */

package battlesys.frontend;

import battlesys.PlayerList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Peter
 */
public class PlayerListForm extends javax.swing.JFrame {

    List<PlayerList> players;
    private int maxCol;
    private DetailedPlayerInfoForm detailedForm;

    /** Creates new form PlayerInfoForm */
    public PlayerListForm(List<PlayerList> players) {
        this.players = players;
        this.detailedForm = new DetailedPlayerInfoForm();
        //find out the max number of players in any team
        maxCol = 0;
        for (PlayerList p : players){
            if (p.size() > maxCol){
                maxCol = p.size();
            }
        }
        initComponents();
    }

    private String[][] createPlayerList(List<PlayerList> p){
        String[][] r = new String[p.size()][maxCol+1];
        for (int i = 0; i < p.size(); ++i){
            r[i][0] = p.get(i).get(0).getTeamName();
            for (int j = 0; j < p.get(i).size(); ++j){
                r[i][j + 1] = p.get(i).get(j).getName();
            }
        }
        return r;
    }

    private String[] createTitle(){
        String[] r = new String[maxCol+1];
        for (int i = 2; i < r.length; ++i){
            r[i] = "";
        }
        r[0] = "隊伍名稱";
        r[1] = "角色名稱";
        return r;
    }

    private Class[] createTypes(){
        Class[] r = new Class[maxCol+1];
        for (int i = 0; i < r.length; ++i){
            r[i] = java.lang.String.class;
        }
        return r;
    }

    private boolean[] createCanEdit(){
        boolean[] r = new boolean[maxCol+1];
        for (int i = 0; i < r.length; ++i){
            r[i] = false;
        }
        return r;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "UseOfObsoleteCollectionType"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonDetailedInfo = new javax.swing.JButton();

        setTitle(NthBattleForm.APP_NAME);

        okButton.setText("確定 OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                okButtonMousePressed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        table.setModel(new javax.swing.table.DefaultTableModel(
            createPlayerList(this.players),
            createTitle()
        ) {
            Class[] types = createTypes();
            boolean[] canEdit = createCanEdit();

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowSelectionAllowed(false);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        buttonDetailedInfo.setText("詳細資料 Details");
        buttonDetailedInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonDetailedInfoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDetailedInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(buttonDetailedInfo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMousePressed
        this.setVisible(false);
    }//GEN-LAST:event_okButtonMousePressed

    private void buttonDetailedInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDetailedInfoMousePressed
        int row = table.getSelectedRow();
        int col = table.getSelectedColumn();
        if (row == -1 || col <= 0 || col > players.get(row).size()){
            JOptionPane.showMessageDialog(this, "你必須選擇一個角色", NthBattleForm.APP_NAME, JOptionPane.ERROR_MESSAGE);
            return;
        }
        detailedForm.setPlayer(players.get(row).get(col-1));
        detailedForm.setVisible(true);
    }//GEN-LAST:event_buttonDetailedInfoMousePressed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.getSelectedRow();
        int col = table.getSelectedColumn();
        if (row == -1 || col <= 0 || col > players.get(row).size()){
            return;
        }
        detailedForm.setPlayer(players.get(row).get(col-1));
    }//GEN-LAST:event_tableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDetailedInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
